// eslint-disable-next-line @typescript-eslint/no-var-requires
const tokens = require('@ramsey-design-system/tokens');

module.exports = {
  content: ['./src/**/*.{html,js,ts,tsx}'],
  theme: {
    extend: {
      maxWidth: {
        '4.5xl': '61rem/* 976px */',
        half: '50%',
      },
      spacing: {
        18: '4.5rem/* 72px */',
      },
      transitionTimingFunction: {
        'cubic-ramp': 'cubic-bezier(0.8, 0.2, 0.2, 0.8)',
      },
    },
    borderRadius: {
      none: tokens.SizeRadiusNone,
      sm: tokens.SizeRadiusSm,
      md: tokens.SizeRadiusMd,
      lg: tokens.SizeRadiusLg,
      full: tokens.SizeRadiusFull,
    },
    borderWidth: {
      0: tokens.SizeBorderNone,
      sm: tokens.SizeBorderSm,
      md: tokens.SizeBorderMd,
      lg: tokens.SizeBorderLg,
      xl: tokens.SizeBorderXl,
    },
    boxShadow: {
      none: tokens.ShadowBoxNone,
      sm: tokens.ShadowBoxSm,
      md: tokens.ShadowBoxMd,
      lg: tokens.ShadowBoxLg,
    },
    colors: {
      current: 'currentColor',
      inherit: 'inherit',
      transparent: 'transparent',
      black: tokens.ColorBaseBlack,
      white: tokens.ColorBaseWhite,
      gray: {
        10: tokens.ColorBaseGray10,
        20: tokens.ColorBaseGray20,
        30: tokens.ColorBaseGray30,
        40: tokens.ColorBaseGray40,
        50: tokens.ColorBaseGray50,
        60: tokens.ColorBaseGray60,
        70: tokens.ColorBaseGray70,
        80: tokens.ColorBaseGray80,
        90: tokens.ColorBaseGray90,
      },
      magenta: {
        10: tokens.ColorBaseMagenta10,
        20: tokens.ColorBaseMagenta20,
        30: tokens.ColorBaseMagenta30,
        40: tokens.ColorBaseMagenta40,
        50: tokens.ColorBaseMagenta50,
        60: tokens.ColorBaseMagenta60,
        70: tokens.ColorBaseMagenta70,
        80: tokens.ColorBaseMagenta80,
        90: tokens.ColorBaseMagenta90,
      },
      purple: {
        10: tokens.ColorBasePurple10,
        20: tokens.ColorBasePurple20,
        30: tokens.ColorBasePurple30,
        40: tokens.ColorBasePurple40,
        50: tokens.ColorBasePurple50,
        60: tokens.ColorBasePurple60,
        70: tokens.ColorBasePurple70,
        80: tokens.ColorBasePurple80,
        90: tokens.ColorBasePurple90,
      },
      violet: {
        10: tokens.ColorBaseViolet10,
        20: tokens.ColorBaseViolet20,
        30: tokens.ColorBaseViolet30,
        40: tokens.ColorBaseViolet40,
        50: tokens.ColorBaseViolet50,
        60: tokens.ColorBaseViolet60,
        70: tokens.ColorBaseViolet70,
        80: tokens.ColorBaseViolet80,
        90: tokens.ColorBaseViolet90,
      },
      blue: {
        10: tokens.ColorBaseBlue10,
        20: tokens.ColorBaseBlue20,
        30: tokens.ColorBaseBlue30,
        40: tokens.ColorBaseBlue40,
        50: tokens.ColorBaseBlue50,
        60: tokens.ColorBaseBlue60,
        70: tokens.ColorBaseBlue70,
        80: tokens.ColorBaseBlue80,
        90: tokens.ColorBaseBlue90,
      },
      aqua: {
        10: tokens.ColorBaseAqua10,
        20: tokens.ColorBaseAqua20,
        30: tokens.ColorBaseAqua30,
        40: tokens.ColorBaseAqua40,
        50: tokens.ColorBaseAqua50,
        60: tokens.ColorBaseAqua60,
        70: tokens.ColorBaseAqua70,
        80: tokens.ColorBaseAqua80,
        90: tokens.ColorBaseAqua90,
      },
      teal: {
        10: tokens.ColorBaseTeal10,
        20: tokens.ColorBaseTeal20,
        30: tokens.ColorBaseTeal30,
        40: tokens.ColorBaseTeal40,
        50: tokens.ColorBaseTeal50,
        60: tokens.ColorBaseTeal60,
        70: tokens.ColorBaseTeal70,
        80: tokens.ColorBaseTeal80,
        90: tokens.ColorBaseTeal90,
      },
      green: {
        10: tokens.ColorBaseGreen10,
        20: tokens.ColorBaseGreen20,
        30: tokens.ColorBaseGreen30,
        40: tokens.ColorBaseGreen40,
        50: tokens.ColorBaseGreen50,
        60: tokens.ColorBaseGreen60,
        70: tokens.ColorBaseGreen70,
        80: tokens.ColorBaseGreen80,
        90: tokens.ColorBaseGreen90,
      },
      lime: {
        10: tokens.ColorBaseLime10,
        20: tokens.ColorBaseLime20,
        30: tokens.ColorBaseLime30,
        40: tokens.ColorBaseLime40,
        50: tokens.ColorBaseLime50,
        60: tokens.ColorBaseLime60,
        70: tokens.ColorBaseLime70,
        80: tokens.ColorBaseLime80,
        90: tokens.ColorBaseLime90,
      },
      yellow: {
        10: tokens.ColorBaseYellow10,
        20: tokens.ColorBaseYellow20,
        30: tokens.ColorBaseYellow30,
        40: tokens.ColorBaseYellow40,
        50: tokens.ColorBaseYellow50,
        60: tokens.ColorBaseYellow60,
        70: tokens.ColorBaseYellow70,
        80: tokens.ColorBaseYellow80,
        90: tokens.ColorBaseYellow90,
      },
      amber: {
        10: tokens.ColorBaseAmber10,
        20: tokens.ColorBaseAmber20,
        30: tokens.ColorBaseAmber30,
        40: tokens.ColorBaseAmber40,
        50: tokens.ColorBaseAmber50,
        60: tokens.ColorBaseAmber60,
        70: tokens.ColorBaseAmber70,
        80: tokens.ColorBaseAmber80,
        90: tokens.ColorBaseAmber90,
      },
      orange: {
        10: tokens.ColorBaseOrange10,
        20: tokens.ColorBaseOrange20,
        30: tokens.ColorBaseOrange30,
        40: tokens.ColorBaseOrange40,
        50: tokens.ColorBaseOrange50,
        60: tokens.ColorBaseOrange60,
        70: tokens.ColorBaseOrange70,
        80: tokens.ColorBaseOrange80,
        90: tokens.ColorBaseOrange90,
      },
      red: {
        10: tokens.ColorBaseRed10,
        20: tokens.ColorBaseRed20,
        30: tokens.ColorBaseRed30,
        40: tokens.ColorBaseRed40,
        50: tokens.ColorBaseRed50,
        60: tokens.ColorBaseRed60,
        70: tokens.ColorBaseRed70,
        80: tokens.ColorBaseRed80,
        90: tokens.ColorBaseRed90,
      },
      twitter: tokens.ColorSocialTwitter,
      linkedin: tokens.ColorSocialLinkedin,
      facebook: tokens.ColorSocialFacebook,
      pinterest: tokens.ColorSocialPinterest,
      youtube: tokens.ColorSocialYoutube,
    },
    fontFamily: {
      gibson: [tokens.FontFamilyGibson],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },
    fontSize: {
      1: tokens.SizeFont1,
      2: tokens.SizeFont2,
      3: tokens.SizeFont3,
      4: tokens.SizeFont4,
      5: tokens.SizeFont5,
      6: tokens.SizeFont6,
      7: tokens.SizeFont7,
      8: tokens.SizeFont8,
      9: tokens.SizeFont9,
      10: tokens.SizeFont10,
      11: tokens.SizeFont11,
      12: tokens.SizeFont12,
      13: tokens.SizeFont13,
    },
    fontWeight: {
      light: tokens.FontWeightLight,
      normal: tokens.FontWeightNormal,
      semibold: tokens.FontWeightSemibold,
      bold: tokens.FontWeightBold,
    },
    screens: {
      'xs-down': { max: '26.5em/*max-width: 424px*/' },
      xs: '26.5625em/*max-width: 425px*/',
      'sm-down': { max: '37.4375em/*max-width: 599px*/' },
      sm: '37.5em/*max-width: 600px*/',
      'sm-md': {
        min: '37.5em/*max-width: 600px*/',
        max: '56.1875em/*max-width: 899px*/',
      },
      'sm-lg': {
        min: '37.5em/*max-width: 600px*/',
        max: '74.9375em/*max-width: 1199px*/',
      },
      'sm-2xl': {
        min: '37.5em/*max-width: 600px*/',
        max: '112.4375em/*max-width: 1799px*/',
      },
      md: '56.25em/*max-width: 900px*/',
      'md-lg': {
        min: '56.25em/*max-width: 600px*/',
        max: '74.9375em/*max-width: 1199px*/',
      },
      'md-2xl': {
        min: '56.25em/*max-width: 900px*/',
        max: '112.4375em/*max-width: 1799px*/',
      },
      lg: '75em/*max-width: 1200px*/',
      'lg-2xl': {
        min: '75em/*max-width: 1200px*/',
        max: '112.4375em/*max-width: 1799px*/',
      },
      xl: '93.75em/*max-width: 1600px*/',
      '2xl': '112.5em/*max-width: 1800px*/',
    },
  },
  plugins: [
    function ({ addVariant }) {
      addVariant('child', '& > *');
      addVariant('child-hover', '& > *:hover');
    },
  ],
};
